### ISSUE TITLE
Open Tasks

### ISSUE THREAD

**Issue by marshalluous** [raphiz/WED2-Testat#1]
In ListeView:
- [x] Filter: By Finish Date
- [x] Filter By Importance
- [x] Filter By created
- [x] Filter: fertige Verbergen
- [x] Style Switcher
- [x] responsive design verbessern

**Comment by marshalluous** [comment]
Bin gerade dran an: 
Filter: fertige Verbergen

**Comment by raphiz** [comment]
@marshalluous habe die Liste umgeschrieben und mein aktueller stand eingecheckt. Wir müssen nun (meineswissens nach) nur noch das Responsive Design in den Griff bekommen (Ja, hab einiges kaputt gemacht - sory :cry: )

**Comment by marshalluous** [comment]
responsive Design ist nun erledigt. Testat abgeschlossen von unserer Seite her.

**Comment by raphiz** [comment]
Geil :tada:
